spring.application.name=FirmaKurierska
# spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#------statyczna
#spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
#---------dynamiczna
#http://localhost:8080/h2-console
#spring.datasource.url=jdbc:h2:~/test 
#jako serwer
#spring.datasource.url=jdbc:h2:tcp://localhost:9092/~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

#spring.jpa.defer-datasource-initialization=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.open-in-view=false
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

server.error.include-stacktrace=never

#------------------------Mysql 
spring.datasource.url=jdbc:mysql://localhost:3306/firma_kurierska
spring.datasource.username=dbuser
spring.datasource.password=dbuser123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect